<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LaddaUpBuild</name>
   <tag></tag>
   <elementGuidId>ba6e0811-7890-44e5-9b12-556489593703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-security/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[9]/div/div/div/div[2]/div/input
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
