<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LaddaUpBuild</name>
   <tag></tag>
   <elementGuidId>3fbd28a9-1146-4402-a60b-fe736fa14a88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-other-water/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[7]/div/div/div/div[2]/div/input
</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
