<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Golvbrunn</name>
   <tag></tag>
   <elementGuidId>54be0d5a-69c3-4cf4-9c4f-c04cfdfe4457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-utility-room1/div/div[2]/div/div[contains(@class,'detail-wrapper')]/div[3]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
